### ISSUE TITLE
no new data

### ISSUE THREAD

**Issue by addiaddiaddi** [skillz-blockchain/sandwalker#3]
sandwalker isn't reporting any recent rewards, probably due to the 7.0 update

**Comment by aimxhaisse** [comment]
Thanks for the report!

I've been trying to fix it but I can't, it's stuck due to this issue:

https://github.com/pokt-network/pocket-core/issues/1382

Sandwalker needs to compute all blocks to fetch all rewards, but it seems that currently, the blockchain is in an invalid state and can't be processed block by block. This is not an issue for node runners because they just use snapshots from the Pocket team (but it likely means those snapshots are not correct from a 'chain' perspective either).

**Comment by aimxhaisse** [comment]
I've upgraded to 0.7.1 which should fix this issue, waiting for the sandwalker node to synchronize from block 0 to confirm it's now fixed.
